# -*- coding: utf-8 -*-
"""Detector de caras

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzJg9PUHztijz5kGKrYruy_QsYvmYPnq
"""

import pathlib
import cv2

# Asegúrate de que el archivo Haarcascade esté en la ruta correcta
cascade_path = "haarcascade_fullbody.xml"
print(cascade_path)

# Verifica si el archivo XML existe
if False:
    print(f"Error: No se encontró el archivo {cascade_path}")
else:
    clf = cv2.CascadeClassifier(str(cascade_path))

    camera = cv2.VideoCapture(0)
    if not camera.isOpened():
        print("Error: No se puede acceder a la cámara")
    else:
        while True:
            ret, frame = camera.read()
            if not ret:
                print("Error: No se puede recibir imagen (cámara desconectada?)")
                break
            
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = clf.detectMultiScale(
                gray,
                scaleFactor=1.1,
                minNeighbors=5,
                minSize=(30, 30),
                flags=cv2.CASCADE_SCALE_IMAGE
            )

            for (x, y, width, height) in faces:
                cv2.rectangle(frame, (x, y), (x + width, y + height), (255, 255, 0), 2)

            cv2.imshow("Faces", frame)
            if cv2.waitKey(1) == ord("q"):
                break

        camera.release()
        cv2.destroyAllWindows()
